### ISSUE TITLE
Which os should I installed it?

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/censorship-scanner#3]
Would you clarify?

Thanks

**Comment by alexlii1971** [comment]
got it.

I am on iPhone at home now, will let you know after test tomorrow.

**Comment by Prajwal-Koirala** [comment]
> got it.
> 
> I am on iPhone at home now, will let you know after test tomorrow.

any issue since using the new VPN?

**Comment by alexlii1971** [comment]
No issue, but some local a virus/security software will report outline is a spy software.

Please check it at https://guanjia.qq.com

So I just suppose they are managing network on behalf of government.

But, on that software, they officially claim that it is obligated to the policy and security standards of international security association, that is shame, if possible, just report to security association.

**Comment by Prajwal-Koirala** [comment]
> No issue, but some local a virus/security software will report outline is a spy software.
> 
> Please check it at https://guanjia.qq.com
> 
> So I just suppose they are managing network on behalf of government.
> 
> But, on that software, they officially claim that it is obligated to the policy and security standards of international security association, that is shame, if possible, just report to security association.

Nah dude,
they say that so people don't use it and get scared of it.

You can ignore the errors, the chinese gov will tell you `google.com`, `facebook.com`, `yahoo.com`, `amazon.com` are bad too since they are not controlled by the party.

**Comment by alexlii1971** [comment]
This command: go get -v -u github.com/complexorganizations/censorship-scanner
does not work in Windows, and it show it is not internal command.


On Mac, please check:

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-5:~ leealex1$ go get -v -u github.com/complexorganizations/censorship-scanner

go: downloading github.com/complexorganizations/censorship-scanner v0.0.0-20210611181310-d0687665e734
runtime/cgo
# runtime/cgo
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

MacBook-Pro-5:~ leealex1$ 
MacBook-Pro-5:~ leealex1$ censorship-scanner -advanced
-bash: censorship-scanner: command not found
MacBook-Pro-5:~ leealex1$ 
MacBook-Pro-5:~ leealex1$ 
```

**Comment by alexlii1971** [comment]
I changed to use this terminal : https://iterm2.com/features.html

and it show:
leealex1@MacBook-Pro-5 ~ % go get -v -u github.com/complexorganizations/censorship-scanner

runtime/cgo
# runtime/cgo
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

It seems that I need setup developer enviroment?
If yes, What or how should I do?

**Comment by Prajwal-Koirala** [comment]
hey, the issue is that your system doesn't have the required tools for this to work, so just do.

```
xcode-select --install
```
If that doesn’t work, force it to reset. You’ll need `sudo` access for this one.

```
sudo xcode-select --reset
```

**Comment by alexlii1971** [comment]
just wait for minutes...

**Comment by alexlii1971** [comment]
Should we chat on Whatsapp?

**Comment by Prajwal-Koirala** [comment]
sure, i am going to download it again.

**Comment by alexlii1971** [comment]
ok, text me on whatsapp

**Comment by Prajwal-Koirala** [comment]
send me a message
